spring:
  application:
    name: ESOP

  datasource:
    url: JDBC:mysql://localhost:3306/exp_config
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /ESOP

  port: 8081