spring.application.name=ESOP
server.servlet.context-path=/ESOP
spring.datasource.url=jdbc:mysql://localhost:3306/exp_config
spring.datasource.user-name=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
